### ISSUE TITLE
localization for plugins

### ISSUE THREAD

**Issue by tlambert03** [tlambert03/npe2#19]
Some stuff we discussed in the meeting today is how to help plugins provide translation strings

in zulip previously, I had shown how vscode does this:
```yml
# main manifest file
contributes:
  commands:
    - command: my_plugin.hello_world
      title: '%my_plugin.hello_world.title%'
# my_plugin.nls.en.yaml
my_plugin.hello_world.title : Hello!
```

@goanpeca pointed out that this key-based method has some downsides and is tough to combine with the "string-as-key" method that we currently use.  Instead, we could just identify certain fields in the manifest like "display_text" or "title" etc that we offer to translate.  

```py
class Manifest(BaseModel):
    some_field: str = Field(..., extra={'translatable': True})  # or whatever ... 
```

In addition we will scan the plugin code itself for `trans._()` calls.

Exactly how that all gets to crowdin and how plugin translation packs make their way back into napari at runtime is still a little foggy to me.
