### ISSUE TITLE
need spec for package-relative paths

### ISSUE THREAD

**Issue by tlambert03** [tlambert03/npe2#33]
in sample data, it's possible that someone will ship a tif file or something in their package.  Before, they could use `Path(__file__).parent...` to point to it, but not in a static manifest,

One proposal is to use `${package}`:
```yaml
sample_data:
  - display_name: Some image
    key: some_image
    uri: ${package}/data/some_image.tif
```

@Carreau, @nclack ?

**Comment by nclack** [comment]
It seems like they could use `SampleDataGenerator` to load a bundled asset.  Is that right?

It does seem like something the manifest might help with.  I like how we have `SampleDataGenerator` and `SampleDataURI` to specify different ways of accessing the data.  What do you think about something like this?

```yaml
sample_data:
  - display_name: Some image
    key: some_image
    package_data: my_sample.data:some_image.tif
```

I think the using a string-interpolated variable (what you proposed) works.  I wonder about alternatives though.
